// we restrict the type of exception that a function can throw outside of itself
// Wap to illustrate the concept of handling uncaught

#include<iostream>
#include<cstdlib>
#include
using namespace std;

int main(){
    
    return 0;
}